export interface CorporateActionData {
  annualDividendPerShare: number;
  dividendYieldPct: number;
  dividendFrequency: string;
  nextExDate: string;
  nextPaymentDate: string;
  payoutType: "Cash Dividend (Auto-Credit)" | "Growth Reinvestment" | "BTC Reserve Treasury";
  dtcCustodian: string;
  secFilingType: "10-Q (Quarterly)" | "10-K (Annual)" | "S-1 Filing";
  lastFilingDate: string;
  nextEarningsEstimate: string;
}

export const STOCK_CORPORATE_ACTIONS: Record<string, CorporateActionData> = {
  AAPLc: {
    annualDividendPerShare: 1.00,
    dividendYieldPct: 0.44,
    dividendFrequency: "Quarterly ($0.25/sh)",
    nextExDate: "Nov 08, 2026",
    nextPaymentDate: "Nov 14, 2026",
    payoutType: "Cash Dividend (Auto-Credit)",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Jul 31, 2026",
    nextEarningsEstimate: "Oct 29, 2026",
  },
  MSFTc: {
    annualDividendPerShare: 3.32,
    dividendYieldPct: 0.74,
    dividendFrequency: "Quarterly ($0.83/sh)",
    nextExDate: "Nov 20, 2026",
    nextPaymentDate: "Dec 11, 2026",
    payoutType: "Cash Dividend (Auto-Credit)",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Jul 30, 2026",
    nextEarningsEstimate: "Oct 24, 2026",
  },
  NVDAc: {
    annualDividendPerShare: 0.04,
    dividendYieldPct: 0.03,
    dividendFrequency: "Quarterly ($0.01/sh)",
    nextExDate: "Dec 04, 2026",
    nextPaymentDate: "Dec 26, 2026",
    payoutType: "Cash Dividend (Auto-Credit)",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Aug 28, 2026",
    nextEarningsEstimate: "Nov 19, 2026",
  },
  GOOGLc: {
    annualDividendPerShare: 0.80,
    dividendYieldPct: 0.48,
    dividendFrequency: "Quarterly ($0.20/sh)",
    nextExDate: "Dec 08, 2026",
    nextPaymentDate: "Dec 15, 2026",
    payoutType: "Cash Dividend (Auto-Credit)",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Jul 23, 2026",
    nextEarningsEstimate: "Oct 22, 2026",
  },
  METAc: {
    annualDividendPerShare: 2.00,
    dividendYieldPct: 0.35,
    dividendFrequency: "Quarterly ($0.50/sh)",
    nextExDate: "Dec 14, 2026",
    nextPaymentDate: "Dec 23, 2026",
    payoutType: "Cash Dividend (Auto-Credit)",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Jul 31, 2026",
    nextEarningsEstimate: "Oct 30, 2026",
  },
  INTCc: {
    annualDividendPerShare: 0.50,
    dividendYieldPct: 2.15,
    dividendFrequency: "Quarterly ($0.125/sh)",
    nextExDate: "Nov 06, 2026",
    nextPaymentDate: "Dec 01, 2026",
    payoutType: "Cash Dividend (Auto-Credit)",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Aug 01, 2026",
    nextEarningsEstimate: "Oct 24, 2026",
  },
  COINc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (Growth Reinvestment)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "Growth Reinvestment",
    dtcCustodian: "DTC Eligible / Coinbase Custody Broker Partner",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Aug 01, 2026",
    nextEarningsEstimate: "Oct 31, 2026",
  },
  TSLAc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (Growth Reinvestment)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "Growth Reinvestment",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Jul 23, 2026",
    nextEarningsEstimate: "Oct 16, 2026",
  },
  AMZNc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (Growth Reinvestment)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "Growth Reinvestment",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Aug 01, 2026",
    nextEarningsEstimate: "Oct 24, 2026",
  },
  MSTRc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (BTC Accumulation)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "BTC Reserve Treasury",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Aug 01, 2026",
    nextEarningsEstimate: "Oct 30, 2026",
  },
  CRCLc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (Pre-IPO Growth)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "Growth Reinvestment",
    dtcCustodian: "Institutional Custody Partner",
    secFilingType: "S-1 Filing",
    lastFilingDate: "Jun 15, 2026",
    nextEarningsEstimate: "Q4 2026",
  },
  SNDKc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (Growth Reinvestment)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "Growth Reinvestment",
    dtcCustodian: "DTC Eligible / Licensed US Broker-Custodian",
    secFilingType: "10-Q (Quarterly)",
    lastFilingDate: "Jul 25, 2026",
    nextEarningsEstimate: "Nov 05, 2026",
  },
  SPCXc: {
    annualDividendPerShare: 0.00,
    dividendYieldPct: 0.00,
    dividendFrequency: "N/A (Private Equity Growth)",
    nextExDate: "N/A",
    nextPaymentDate: "N/A",
    payoutType: "Growth Reinvestment",
    dtcCustodian: "Qualified Institutional Custodian",
    secFilingType: "S-1 Filing",
    lastFilingDate: "May 20, 2026",
    nextEarningsEstimate: "Q4 2026",
  },
};
