/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as IndicesIdRouteImport } from './routes/indices_.$id'
import { Route as IndicesCreateRouteImport } from './routes/indices_.create'
import { Route as StockAddressRouteImport } from './routes/stock.$address'
import { Route as StocksSymbolRouteImport } from './routes/stocks_.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesIdRoute = IndicesIdRouteImport.update({
  id: '/indices_/$id',
  path: '/indices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesCreateRoute = IndicesCreateRouteImport.update({
  id: '/indices_/create',
  path: '/indices/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAddressRoute = StockAddressRouteImport.update({
  id: '/stock/$address',
  path: '/stock/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks_/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indices': typeof IndicesRoute
  '/swap': typeof SwapRoute
  '/indices/$id': typeof IndicesIdRoute
  '/indices/create': typeof IndicesCreateRoute
  '/stock/$address': typeof StockAddressRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indices': typeof IndicesRoute
  '/swap': typeof SwapRoute
  '/indices/$id': typeof IndicesIdRoute
  '/indices/create': typeof IndicesCreateRoute
  '/stock/$address': typeof StockAddressRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indices': typeof IndicesRoute
  '/swap': typeof SwapRoute
  '/indices_/$id': typeof IndicesIdRoute
  '/indices_/create': typeof IndicesCreateRoute
  '/stock/$address': typeof StockAddressRoute
  '/stocks_/$symbol': typeof StocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/indices'
    | '/swap'
    | '/indices/$id'
    | '/indices/create'
    | '/stock/$address'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/indices'
    | '/swap'
    | '/indices/$id'
    | '/indices/create'
    | '/stock/$address'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/indices'
    | '/swap'
    | '/indices_/$id'
    | '/indices_/create'
    | '/stock/$address'
    | '/stocks_/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndicesRoute: typeof IndicesRoute
  SwapRoute: typeof SwapRoute
  IndicesIdRoute: typeof IndicesIdRoute
  IndicesCreateRoute: typeof IndicesCreateRoute
  StockAddressRoute: typeof StockAddressRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices_/$id': {
      id: '/indices_/$id'
      path: '/indices/$id'
      fullPath: '/indices/$id'
      preLoaderRoute: typeof IndicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices_/create': {
      id: '/indices_/create'
      path: '/indices/create'
      fullPath: '/indices/create'
      preLoaderRoute: typeof IndicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$address': {
      id: '/stock/$address'
      path: '/stock/$address'
      fullPath: '/stock/$address'
      preLoaderRoute: typeof StockAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks_/$symbol': {
      id: '/stocks_/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndicesRoute: IndicesRoute,
  SwapRoute: SwapRoute,
  IndicesIdRoute: IndicesIdRoute,
  IndicesCreateRoute: IndicesCreateRoute,
  StockAddressRoute: StockAddressRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
